package coursework234;

import java.net.*;
import java.io.*;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


public class myJFrame extends javax.swing.JFrame implements Serializable {

    public myJFrame() {
        try {
            initComponents();

            this.s = new Socket("127.0.0.1", 2000);
            this.objOS = new ObjectOutputStream(s.getOutputStream());
            this.objIS = new ObjectInputStream(s.getInputStream());
        } catch (IOException ex) {
            System.out.printf("Error connecting with the Server %s\n", ex);
            //    Logger.getLogger(myJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jtStoreroom = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPurchase = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfPurchaseOrderID = new javax.swing.JTextField();
        jtfDateCreated = new javax.swing.JTextField();
        jtfExpectedDeliveryDate = new javax.swing.JTextField();
        jtfSupplier = new javax.swing.JTextField();
        jcbStatus = new javax.swing.JComboBox();
        jcbCompletedStatus = new javax.swing.JComboBox();
        jbNewPO = new javax.swing.JButton();
        jbDeletePO = new javax.swing.JButton();
        jbUpdatePO = new javax.swing.JButton();
        jbRefreshPO = new javax.swing.JButton();
        jbInsertPO = new javax.swing.JButton();
        jbPrint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPurchaseline = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purchase Managerment");
        setAlwaysOnTop(true);

        jPanel1.setName(""); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PurchaseOrderID", "DateCreated", "ExpectedDeliveryDate", "Supplier", "Status", "CompletedStatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPurchase.getTableHeader().setReorderingAllowed(false);
        jtPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPurchaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPurchase);

        jLabel1.setText("Purchase Order ID:");

        jLabel2.setText("Date Created:");

        jLabel3.setText("Expected Delivery Date:");

        jLabel4.setText("Supplier:");

        jLabel5.setText("Status:");

        jLabel6.setText("Completed Status:");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtPurchase, org.jdesktop.beansbinding.ELProperty.create("${(selectedElement!= null)}"), jtfPurchaseOrderID, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtPurchase, org.jdesktop.beansbinding.ELProperty.create("${(selectedElement!= null)}"), jtfDateCreated, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtPurchase, org.jdesktop.beansbinding.ELProperty.create("${(selectedElement!= null)}"), jtfExpectedDeliveryDate, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtPurchase, org.jdesktop.beansbinding.ELProperty.create("${(selectedElement!= null)}"), jtfSupplier, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Completed", "Dispatched", "Cancelled", "On_Hold", "Order" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtPurchase, org.jdesktop.beansbinding.ELProperty.create("${(selectedElement!= null)}"), jcbStatus, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jcbCompletedStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No", "Yes" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtPurchase, org.jdesktop.beansbinding.ELProperty.create("${(selectedElement!= null)}"), jcbCompletedStatus, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jbNewPO.setText("New");
        jbNewPO.setToolTipText("Click New, then click the blank row in the table,start a record!");
        jbNewPO.setName("jbNewPO"); // NOI18N
        jbNewPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNewPOjbNew_PO_ActionPerformed(evt);
            }
        });

        jbDeletePO.setText("Delete");
        jbDeletePO.setName("jbDeletePO"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtPurchase, org.jdesktop.beansbinding.ELProperty.create("${(selectedElement!= null)}"), jbDeletePO, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jbDeletePO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletePOjbDelete_PO_ActionPerformed(evt);
            }
        });

        jbUpdatePO.setText("Update");
        jbUpdatePO.setName("jbUpdatePO"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtPurchase, org.jdesktop.beansbinding.ELProperty.create("${(selectedElement!= null)}"), jbUpdatePO, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jbUpdatePO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdatePOjbUpdate_PO_ActionPerformed(evt);
            }
        });

        jbRefreshPO.setText("Refresh");
        jbRefreshPO.setName("jbRefreshPO"); // NOI18N
        jbRefreshPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRefreshPOjbRefresh_PO_ActionPerformed(evt);
            }
        });

        jbInsertPO.setText("Insert");
        jbInsertPO.setName("jbInsertPO"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jtPurchase, org.jdesktop.beansbinding.ELProperty.create("${(selectedElement!= null)}"), jbInsertPO, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jbInsertPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInsertPOjbInsert_PO_ActionPerformed(evt);
            }
        });

        jbPrint.setText("Print");
        jbPrint.setName("jbPrint"); // NOI18N
        jbPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrint_PO_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfExpectedDeliveryDate, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jtfDateCreated, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jtfPurchaseOrderID)
                                    .addComponent(jtfSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                    .addComponent(jcbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbCompletedStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jbNewPO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbDeletePO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbUpdatePO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbRefreshPO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbInsertPO, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfPurchaseOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtfDateCreated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfExpectedDeliveryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jtfSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbCompletedStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNewPO)
                    .addComponent(jbDeletePO)
                    .addComponent(jbUpdatePO)
                    .addComponent(jbRefreshPO)
                    .addComponent(jbInsertPO)
                    .addComponent(jbPrint))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtStoreroom.addTab("Purchase Order", jPanel1);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtPurchaseline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Line ID", "Quantity", "Price Per Unit", "PurchaseOrderNum", "PartID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPurchaseline.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtPurchaseline);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtStoreroom.addTab("Purchase Order Line", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PartID", "Manufacturer", "Manufacturer Description", "Component Description", "Current Stock Level", "Low Stock Level", "Shelf Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtStoreroom.addTab("Store Room", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtStoreroom)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtStoreroom)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNewPOjbNew_PO_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNewPOjbNew_PO_ActionPerformed

        jbUpdatePO.setVisible(false);
        DefaultTableModel purchaseModel = (DefaultTableModel) jtPurchase.getModel();
        cleanField();

        purchaseModel.addRow(new Object[]{
            jtfPurchaseOrderID.getText(),
            jtfDateCreated.getText(),
            jtfExpectedDeliveryDate.getText(),
            jtfSupplier.getText(),
            jcbStatus.getSelectedItem(),
            jcbCompletedStatus.getSelectedItem()
        });
    }//GEN-LAST:event_jbNewPOjbNew_PO_ActionPerformed

    private void jbDeletePOjbDelete_PO_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletePOjbDelete_PO_ActionPerformed

    }//GEN-LAST:event_jbDeletePOjbDelete_PO_ActionPerformed

    private void jbUpdatePOjbUpdate_PO_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdatePOjbUpdate_PO_ActionPerformed

    }//GEN-LAST:event_jbUpdatePOjbUpdate_PO_ActionPerformed

    private void jbRefreshPOjbRefresh_PO_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRefreshPOjbRefresh_PO_ActionPerformed
        DefaultTableModel purchaseModel = (DefaultTableModel) jtPurchase.getModel();
        String name = jbRefreshPO.getName();

        purchaseOrder p = new purchaseOrder();
        p.setKey(name);

        try {
            System.out.printf("Sending start!");
            this.objOS.writeObject(p);//发到服务器
            this.objOS.flush();//清空输出流
            p = (purchaseOrder) objIS.readObject();//接收回复
            System.out.printf("Sending and Receivig Finish!");
        } catch (Exception ex) {
            Logger.getLogger(myJFrame.class.getName()).log(Level.SEVERE, null, ex);
            System.out.printf("Problem with send or receive %s\n", ex);

        }

        ArrayList<String> refreshResult = p.getRefreshResult();

        while (purchaseModel.getRowCount() > 0) {
            purchaseModel.removeRow(purchaseModel.getRowCount() - 1);
        }
        int size = refreshResult.size();
         System.out.println(size);
         
      
        for (int i = 0; i <=refreshResult.size()/7; i++) {
        purchaseModel.addRow(new Object[]{
        refreshResult.get(6*i+0),
        refreshResult.get(6*i+1),//Display Data into Jtable
        refreshResult.get(6*i+2),
        refreshResult.get(6*i+3),
        refreshResult.get(6*i+4),
        refreshResult.get(6*i+5),}
        );
        }
        
     

    }//GEN-LAST:event_jbRefreshPOjbRefresh_PO_ActionPerformed

    private void jbInsertPOjbInsert_PO_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInsertPOjbInsert_PO_ActionPerformed
//        purchaseOrder.setPurchaseOrderInput(jtfPurchaseOrderID, jtfDateCreated, jtfExpectedDeliveryDate, jtfSupplier, jcbStatus, jcbCompletedStatus);
//        purchaseOrder.setKey(jbInsertPO.getName());
//        srData();

    }//GEN-LAST:event_jbInsertPOjbInsert_PO_ActionPerformed

    private void jbPrint_PO_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrint_PO_ActionPerformed

    }//GEN-LAST:event_jbPrint_PO_ActionPerformed

    private void jtPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPurchaseMouseClicked
       DefaultTableModel purchaseModel = (DefaultTableModel) jtPurchase.getModel();
        jtfPurchaseOrderID.setText(purchaseModel.getValueAt(jtPurchase.getSelectedRow(), 0).toString());
        jtfDateCreated.setText(purchaseModel.getValueAt(jtPurchase.getSelectedRow(), 1).toString());
        jtfExpectedDeliveryDate.setText(purchaseModel.getValueAt(jtPurchase.getSelectedRow(), 2).toString());
        jtfSupplier.setText(purchaseModel.getValueAt(jtPurchase.getSelectedRow(), 3).toString());
        jcbStatus.setSelectedItem(purchaseModel.getValueAt(jtPurchase.getSelectedRow(), 4).toString());
        jcbCompletedStatus.setSelectedItem(purchaseModel.getValueAt(jtPurchase.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_jtPurchaseMouseClicked

    private void srData() {
//        try {
//            System.out.printf("Sending start!");
//            this.objOS.writeObject(this.purchaseOrder);//发到服务器
//            this.objOS.flush();//清空输出流
//            this.purchaseOrder = (purchaseOrder) objIS.readObject();//接收回复
//            System.out.printf("Sending and Receivig Finish!");
//        } catch (Exception ex) {
//            Logger.getLogger(myJFrame.class.getName()).log(Level.SEVERE, null, ex);
//            System.out.printf("Problem with send or receive %s\n", ex);
//
//        }

    }

    private void cleanField() {
        String name = jbNewPO.getName();
        System.out.println(name);

        jtfPurchaseOrderID.setText("");
        jtfDateCreated.setText("");
        jtfExpectedDeliveryDate.setText("");
        jtfSupplier.setText("");
        jcbStatus.setSelectedItem("");
        jcbCompletedStatus.setSelectedItem("");
        /*
         jtfPricePerUnit.setText("0");
         jtfQuantity.setText("0");
         jtfLineID.setText("");
         jcbPurchaseOrder.setSelectedItem("");
         jcbPartID.setSelectedItem("");

         jtfPartID.setText("");
         jtfManufacturer.setText("");
         jtfManufacturerDesc.setText("");
         jtfComponentDesc.setText("");
         jtfCurrentStock.setText("");
         jtfLowStock.setText("");
         jtfShelfLoc.setText("");

         purchaseorderline.getItemToComboBox(jcbPurchaseOrder, "purchaseorder", "PurchaseOrderID");
         purchaseorderline.getItemToComboBox(jcbPartID, "storeroom", "PartID");
         */
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton jbDeletePO;
    private javax.swing.JButton jbInsertPO;
    private javax.swing.JButton jbNewPO;
    private javax.swing.JButton jbPrint;
    private javax.swing.JButton jbRefreshPO;
    private javax.swing.JButton jbUpdatePO;
    private javax.swing.JComboBox jcbCompletedStatus;
    private javax.swing.JComboBox jcbStatus;
    private javax.swing.JTable jtPurchase;
    private javax.swing.JTable jtPurchaseline;
    private javax.swing.JTabbedPane jtStoreroom;
    private javax.swing.JTextField jtfDateCreated;
    private javax.swing.JTextField jtfExpectedDeliveryDate;
    private javax.swing.JTextField jtfPurchaseOrderID;
    private javax.swing.JTextField jtfSupplier;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
//    private purchaseOrder purchaseOrder ;
    private Socket s;
    private ObjectInputStream objIS = null;
    private ObjectOutputStream objOS = null;

}
